// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llatuyckpkfpojghmcdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsYXR1eWNrcGtmcG9qZ2htY2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTUzMDAsImV4cCI6MjA2MzgzMTMwMH0.1wgK_crm8pE3Bz0E74QKM_8ZbFVk0SFJBcIihwDKgGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);